// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuJNhMlBqtcTdZpO7z3av-9E7Y_aNBlPg',
    appId: '1:968845792466:web:bf62f3c52f9db428d7090b',
    messagingSenderId: '968845792466',
    projectId: 'spendwise-1f666',
    authDomain: 'spendwise-1f666.firebaseapp.com',
    storageBucket: 'spendwise-1f666.firebasestorage.app',
    measurementId: 'G-C04ESP9X49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHKfnVfdMlMaB3PMDLPRiexYl8Vl3ZD0',
    appId: '1:968845792466:android:4eada679000893d6d7090b',
    messagingSenderId: '968845792466',
    projectId: 'spendwise-1f666',
    storageBucket: 'spendwise-1f666.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWxASp3TDMAIAXR1iBQFaEkzQgUbf1hFg',
    appId: '1:968845792466:ios:e5bf797bbdec6c69d7090b',
    messagingSenderId: '968845792466',
    projectId: 'spendwise-1f666',
    storageBucket: 'spendwise-1f666.firebasestorage.app',
    iosBundleId: 'com.example.spendwiseai',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWxASp3TDMAIAXR1iBQFaEkzQgUbf1hFg',
    appId: '1:968845792466:ios:e5bf797bbdec6c69d7090b',
    messagingSenderId: '968845792466',
    projectId: 'spendwise-1f666',
    storageBucket: 'spendwise-1f666.firebasestorage.app',
    iosBundleId: 'com.example.spendwiseai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuJNhMlBqtcTdZpO7z3av-9E7Y_aNBlPg',
    appId: '1:968845792466:web:bf62f3c52f9db428d7090b',
    messagingSenderId: '968845792466',
    projectId: 'spendwise-1f666',
    authDomain: 'spendwise-1f666.firebaseapp.com',
    storageBucket: 'spendwise-1f666.firebasestorage.app',
    measurementId: 'G-C04ESP9X49',
  );
}
